### ISSUE TITLE
RUN SAVE LOAD gone

### ISSUE THREAD

**Issue by JOEYMAN10** [Rikerz/VRC#5]
i downloaded the new ROM corrupter with the queue and whenever i go on it there is no run save or load button there 

is their any help

or same problem

**Comment by Rikerz** [comment]
@JOEYMAN10 I have included the changes that @link2x proposed in the latest release. Your issue should be solved. If it is not, please open another issue.

**Comment by ghost** [comment]
its fine i am not using it anymore
